"""Add theme preference to landlord

Revision ID: 1e557953ad73
Revises: 54402fe517bc
Create Date: 2025-07-05 02:45:40.622181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e557953ad73'
down_revision = '54402fe517bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.drop_column('email_sent')

    # ### end Alembic commands ###
