"""add sent email model

Revision ID: 4447028e88c1
Revises: 8a5958be430a
Create Date: 2025-07-22 14:09:09.282015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4447028e88c1'
down_revision = '8a5958be430a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=120), nullable=False),
    sa.Column('recipient', sa.String(length=120), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_email')
    # ### end Alembic commands ###
