"""Add theme preference to landlord

Revision ID: 54402fe517bc
Revises: e080a8c50150
Create Date: 2025-07-02 00:17:20.906162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54402fe517bc'
down_revision = 'e080a8c50150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###
