"""Add missing columns

Revision ID: 63f9472868d6
Revises: af601daa22bb
Create Date: 2025-07-01 11:38:48.809213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f9472868d6'
down_revision = 'af601daa22bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tenant_unit_id_key'), type_='unique')

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('floor_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parking_spaces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balcony', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('furnished', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('air_conditioning', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('heating', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('internet_included', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('utilities_included', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deposit_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('late_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('grace_period_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('grace_period_days')
        batch_op.drop_column('late_fee')
        batch_op.drop_column('deposit_amount')
        batch_op.drop_column('utilities_included')
        batch_op.drop_column('internet_included')
        batch_op.drop_column('heating')
        batch_op.drop_column('air_conditioning')
        batch_op.drop_column('furnished')
        batch_op.drop_column('balcony')
        batch_op.drop_column('parking_spaces')
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('amenities')
        batch_op.drop_column('unit_type')
        batch_op.drop_column('floor_number')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('bedrooms')
        batch_op.drop_column('size')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('tenant_unit_id_key'), ['unit_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
