"""Add missing columns

Revision ID: 94fc10772211
Revises: 63f9472868d6
Create Date: 2025-07-01 11:46:23.164123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fc10772211'
down_revision = '63f9472868d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('id_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('employer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('move_in_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('move_in_date')
        batch_op.drop_column('employer')
        batch_op.drop_column('occupation')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('id_number')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
