"""add landlord email verification fields

Revision ID: e2d5d7d8646e
Revises: 4447028e88c1
Create Date: 2025-07-22 18:17:36.136632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d5d7d8646e'
down_revision = '4447028e88c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.drop_column('email_verification_code')
        batch_op.drop_column('is_email_verified')

    # ### end Alembic commands ###
